//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crypterv2_DevTool.Core {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class PluginTestConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static PluginTestConfig defaultInstance = ((PluginTestConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PluginTestConfig())));
        
        public static PluginTestConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string recentDirectory {
            get {
                return ((string)(this["recentDirectory"]));
            }
            set {
                this["recentDirectory"] = value;
            }
        }
    }
}
